<?php

namespace Shopping\CartBundle\Entity;

/**
 * ProductCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
   
}
