<?php

namespace Shopping\CartBundle\Entity;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateProductQuantity($updatedQuantity, $productId)
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery('UPDATE Shopping\CartBundle\Entity\Products p SET p.productQuantity = :productQuantity WHERE p.id = :id ');
        $query->setParameter('id', $productId);
        $query->setParameter('productQuantity', $updatedQuantity);
        $query->execute();
//        return TRUE;
    } 
    
    
    public function findAllProductData()
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery('
            SELECT DISTINCT p.id,p.productName,p.productPrice,p.productQuantity,c.categoryName
            FROM Shopping\CartBundle\Entity\Products p
            JOIN Shopping\CartBundle\Entity\ProductCategories c WITH c.id = p.categoryId
        ');
        $data = $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        return $data;
    }
    
    
}




 
    