<?php

namespace Shopping\CartBundle\Entity;
use Symfony\Component\HttpFoundation\Session\Session;
/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByname()
    {
        $session = new Session();
        $username = $session->get('username');
        $entityManager = $this->getEntityManager();
        $users = $entityManager->createQuery
                ('
                    SELECT u 
                    FROM Shopping\CartBundle\Entity\Users u 
                    WHERE u.userName=:userName'
                )
        ->setParameter('userName', $username)
        ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY); 
        $userid = $users[0]['id'];
        return $userid;
    }
    
    
    public function ifIssetSession()
    {
        $session= new Session();
        if($session->get('username')){
            return TRUE;
        }else{
            return FALSE;
        }
    }
    
    public function updateCreditLimit($creditlimit, $userid)
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery('UPDATE Shopping\CartBundle\Entity\Users u SET u.userCredit = :userCredit WHERE u.id = :id ');
        $query->setParameter('userCredit', $creditlimit);
        $query->setParameter('id', $userid);
        $query->execute();
    }
    

}
